# Original inference parameters supplied by the author.
sent_max_len: 32
dropout: 0.3
pooling_type: first-last-avg
batch_size: 64
tokenizer_kwargs:
  pad_token: "$"
  mask_token: "."
  unk_token: "?"
  sep_token: "|"
  cls_token: "*"
  do_lower_case: false
  do_basic_tokenize: true
  tokenize_chinese_chars: false
  strip_accents: null
  never_split: null
  clean_up_tokenization_spaces: false
